#!/usr/bin/env bash
# Restore Android SDK path after `expo prebuild` (which regenerates android/).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SDK_DIR="${ANDROID_HOME:-/opt/homebrew/share/android-commandlinetools}"
PROPS="$ROOT/android/local.properties"

if [[ ! -d "$SDK_DIR" ]]; then
  echo "Android SDK not found at: $SDK_DIR"
  echo "Set ANDROID_HOME or install android-commandlinetools."
  exit 1
fi

mkdir -p "$ROOT/android"
cat > "$PROPS" <<EOF
## Auto-generated by scripts/ensure-android-sdk.sh (do not commit secrets here).
sdk.dir=$SDK_DIR
EOF

# Also satisfy Expo's default path lookup when ANDROID_HOME is unset in GUI terminals.
DEFAULT_SDK="$HOME/Library/Android/sdk"
if [[ ! -e "$DEFAULT_SDK" ]]; then
  mkdir -p "$HOME/Library/Android"
  ln -sfn "$SDK_DIR" "$DEFAULT_SDK"
  echo "Linked $DEFAULT_SDK -> $SDK_DIR"
fi

echo "Wrote $PROPS"
echo "sdk.dir=$SDK_DIR"
