/**
 * Google OAuth for React Native using expo-auth-session + expo-web-browser.
 *
 * Unlike the web version that uses Supabase's redirect-based OAuth,
 * we use expo-web-browser to open the OAuth consent page and receive
 * the result back via deep link.
 */
import * as WebBrowser from 'expo-web-browser';
import Constants from 'expo-constants';
import { getSupabase, isSupabaseConfigured, resetSupabaseOAuthClient } from './supabase';
import { resetGoogleCallbackState } from './googleCallbackState';
import AsyncStorage from '@react-native-async-storage/async-storage';

const OAUTH_INTENT_KEY = 'supabase_oauth_intent';

export type OAuthIntent = 'login' | 'signup' | 'link';

export async function peekOAuthIntent(): Promise<OAuthIntent | null> {
  return (await AsyncStorage.getItem(OAUTH_INTENT_KEY)) as OAuthIntent | null;
}

export async function takeOAuthIntent(): Promise<OAuthIntent> {
  const intent = (await peekOAuthIntent()) ?? 'login';
  await AsyncStorage.removeItem(OAUTH_INTENT_KEY);
  return intent;
}

/**
 * Build the redirect URI that Supabase should send the user back to
 * after Google authentication. In Expo Go this is the `exp://` scheme.
 */
import { makeRedirectUri } from 'expo-auth-session';

/**
 * Start the Google OAuth flow using an in-app browser (expo-web-browser).
 */
export async function startGoogleOAuth(intent: OAuthIntent): Promise<string | null> {
  if (!isSupabaseConfigured()) {
    throw new Error('Google sign-in is not configured.');
  }

  resetGoogleCallbackState();
  resetSupabaseOAuthClient();

  await AsyncStorage.setItem(OAUTH_INTENT_KEY, intent);

  const redirectUri = makeRedirectUri({
    path: 'auth/callback'
  });
  console.log('\n=========================================');
  console.log('EXACT REDIRECT URI GENERATED BY EXPO:');
  console.log(redirectUri);
  console.log('Ensure this EXACT url is in your Supabase Redirect URLs allowlist!');
  console.log('=========================================\n');
  const supabase = getSupabase();

  const { data, error } = await supabase.auth.signInWithOAuth({
    provider: 'google',
    options: {
      queryParams: { prompt: 'select_account' },
      skipBrowserRedirect: true,
      redirectTo: redirectUri,
    },
  });

  if (error || !data.url) {
    await AsyncStorage.removeItem(OAUTH_INTENT_KEY);
    throw new Error(error?.message || 'Could not start Google sign-in');
  }

  // Open in system browser
  const result = await WebBrowser.openAuthSessionAsync(data.url, redirectUri);

  if (result.type === 'success' && result.url) {
    // Extract the access token from the callback URL
    const url = new URL(result.url);
    const hashParams = new URLSearchParams(
      url.hash.startsWith('#') ? url.hash.slice(1) : url.hash,
    );
    const searchParams = url.searchParams;

    const accessToken =
      hashParams.get('access_token') || searchParams.get('access_token');
    const code = searchParams.get('code');

    if (accessToken) {
      return accessToken;
    }

    // If we got a code, exchange it via Supabase
    if (code) {
      const { data: sessionData, error: sessionError } =
        await supabase.auth.exchangeCodeForSession(code);
      if (sessionError || !sessionData.session?.access_token) {
        throw new Error(
          sessionError?.message || 'Failed to exchange code for session',
        );
      }
      return sessionData.session.access_token;
    }

    throw new Error('Google sign-in did not return an access token.');
  }

  // User cancelled or dismissed
  await AsyncStorage.removeItem(OAUTH_INTENT_KEY);
  return null; // Cancelled — not an error
}
